#!/bin/bash

if [ -z $JAVAC ];
then
	JAVAC=javac
fi

#BCP="-bootclasspath /home/rob/CP/INSTALL/classpath/share/classpath/glibj.zip"

$JAVAC -source 1.5 $BCP -nowarn -Xlint:deprecation -classpath .:lib/mysql-connector-java-5.0.5-bin.jar:lib/jfreechart-1.0.4.jar:lib/jcommon-1.0.8.jar:lib/xstream-1.2.2-20061111.171510-1.jar:lib/xpp3_min-1.1.4c.jar:lib/jyaml-1.3.jar -Xlint:unchecked  net/relet/freimap/*.java net/relet/freimap/background/*.java && ( rm freimap.jar ; jar cvfm freimap.jar META-INF/MANIFEST.MF LICENCE README  net/relet/freimap/*.class net/relet/freimap/background/*.class gfx/*.* data/*.* )
