-- Server version	4.1.13

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `FLOWS`
--

DROP TABLE IF EXISTS `FLOWS`;
CREATE TABLE `FLOWS` (
  `RECNUM` bigint(20) unsigned zerofill NOT NULL auto_increment,
  `PROBE` varchar(16) NOT NULL default '',
  `TIME_RECEIVED` datetime NOT NULL default '0000-00-00 00:00:00',
  `FLOW_VERSION` tinyint(4) NOT NULL default '0',
  `SEQUENCE` bigint(20) unsigned zerofill NOT NULL default '00000000000000000000',
  `SOURCE_IP` varchar(16) NOT NULL default '',
  `SOURCE_PORT` int(11) NOT NULL default '0',
  `DEST_IP` varchar(16) NOT NULL default '',
  `DEST_PORT` int(11) NOT NULL default '0',
  `NEXT_HOP` varchar(16) NOT NULL default '',
  `PROTOCOL` int(11) NOT NULL default '0',
  `TCP_FLAGS` int(11) NOT NULL default '0',
  `TOS` int(11) NOT NULL default '0',
  `BYTES` bigint(20) unsigned NOT NULL default '0',
  `PACKETS` bigint(20) unsigned NOT NULL default '0',
  `FLOW_BEGIN` datetime NOT NULL default '0000-00-00 00:00:00',
  `FLOW_END` datetime NOT NULL default '0000-00-00 00:00:00',
  `SOURCE_AS` int(11) NOT NULL default '0',
  `DEST_AS` int(11) NOT NULL default '0',
  `SOURCE_MASK` smallint(6) NOT NULL default '0',
  `DEST_MASK` smallint(6) NOT NULL default '0',
  PRIMARY KEY  (`RECNUM`),
  KEY `k_begin` (`FLOW_BEGIN`),
  KEY `k_end` (`FLOW_END`),
  KEY `k_time` (`TIME_RECEIVED`),
  KEY `k_src` (`SOURCE_IP`),
  KEY `k_dst` (`DEST_IP`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

